// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoginController from "./login_controller"
application.register("login", LoginController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import TaskDoneController from "./task_done_controller"
application.register("task-done", TaskDoneController)
